source/conf-netlify/conf.py
modified:   source/conf-netlify/conf.py
=> PBM-747 Added GA account

source/installation.rst
dquote>
dquote> modified:   source/installation.rst
=> PBM-762 Updated minimal Go version

README.md, source/index.rst
modified:   source/index.rst
modified:   README.md
=> Updated min supported MongoDB version

source/configuration-options.rst, source/point-in-time-recovery.rst
modified:   source/configuration-options.rst
modified:   source/point-in-time-recovery.rst
=> PBM-770 PITR compression description

source/configuration-options.rst, source/installation.rst, source/storage-configuration.rst
modified:   source/configuration-options.rst
modified:   source/installation.rst
modified:   source/storage-configuration.rst
=> PBM-577 Doc S3 storage class support

source/point-in-time-recovery.rst, source/running.rst
modified:   source/point-in-time-recovery.rst
modified:   source/running.rst
=> PBM-716 Add warning about resharding

source/backup-types.rst, source/index.rst, source/initial-setup.rst, source/installation.rst, source/intro.rst, source/pbm-commands.rst, source/point-in-time-recovery.rst, source/running.rst
modified:   source/index.rst
modified:   source/initial-setup.rst
modified:   source/installation.rst
modified:   source/intro.rst
modified:   source/pbm-commands.rst
modified:   source/point-in-time-recovery.rst
modified:   source/running.rst
new file: source/backup-types.rst
=> PBM-755 Added physical backups description into docs

source/conf.py, source/configuration-options.rst, source/index.rst, source/release-notes.rst, source/release-notes/1.7.0.rst, source/upgrading.rst
modified:   source/conf.py
modified:   source/release-notes.rst
new file:   source/release-notes/1.7.0.rst
=> PBM-782 Release notes 1.7.0

source/initial-setup.rst
modified:   source/initial-setup.rst
=> PBM-824 Added Kerberos authentication and other auth methods to docs

source/404.rst
=> PBM-839 Add a 404 page

source/glossary.rst, source/running.rst, source/troubleshooting.rst
modified:   source/glossary.rst
modified:   source/running.rst
modified:   source/troubleshooting.rst
=> PBM-826 Added the complete TS explanation to docs

source/configuration-options.rst
modified:   source/configuration-options.rst
=> PBM-838 Added compression confi paramters for backups

source/pbm-commands.rst
modified:   source/pbm-commands.rst
=> PBM-866 Added the wait flag to pbm backup description

source/backup-types.rst, source/conf.py, source/release-notes.rst, source/release-notes/1.8.0.rst
modified:   source/conf.py
modified:   source/release-notes.rst
new file:   source/release-notes/1.8.0.rst
=> PBM-855 Release notes 1.8.0

source/initial-setup.rst
Added authsource to mongoDB URI connection string examples
=> PBM-720 Updated the URI format

source/intro.rst, source/point-in-time-recovery.rst
Reorded the sequenca of commands and updated the use case
modified: source/intro.rst
=> PBM-883-Update intro page

source/.res/replace.txt, source/backup-types.rst, source/index.rst, source/pbm-commands.rst, source/release-notes/1.7.0.rst, source/running.rst
modified:   source/backup-types.rst
modified:   source/pbm-commands.rst
modified:   source/release-notes/1.7.0.rst
modified:   source/running.rst
modified:   source/index.rst
=> PBM-876 Added a tech preview warning for physical backup

source/conf.py, source/release-notes.rst, source/release-notes/1.8.1.rst
modified:   source/conf.py
modified:   source/release-notes.rst
new file; source/release-notes/1.8.1.rst
=> PBM-892 Release notes 1.8.1

docs/manage/schedule-backup.md
modified:   docs/manage/schedule-backup.md
=> Removed version for Schedule backups section

docs/usage/start-backup.md
=> PBM-982 Removed the tech preview label from physical backups

docs/reference/pbm-commands.md
=> PBM-733 Updated pbm logs command description

docs/index.md, docs/usage/delete-backup.md, docs/usage/oplog-replay.md, docs/usage/point-in-time-recovery.md
modified:   docs/index.md
modified:   docs/usage/delete-backup.md
modified:   docs/usage/oplog-replay.md
modified:   docs/usage/point-in-time-recovery.md
=> PBM-850 Updated delete backups doc

docs/installation.md, docs/usage/restore.md
modified:   docs/installation.md
=> PBM-949 Updated Installation with what nodes not to install on

docs/details/storage-configuration.md, docs/reference/configuration-options.md
modified:   docs/details/storage-configuration.md
modified:   docs/reference/configuration-options.md
=> PBM-922 Documented SSE-C support

docs/release-notes.md, docs/release-notes/2.0.0.md, docs/release-notes/2.0.1.md, mkdocs-base.yml
new file:   docs/release-notes/2.0.1.md
=> PBM-965 Release notes 2.0.1

docs/faq.md
=> PBM-987 Updated FAQ with the info about selective backups

docs/release-notes.md, docs/release-notes/2.0.2.md, mkdocs-base.yml
new file:   docs/release-notes/2.0.2.md
=> PBM-989 Release notes 2.0.2

docs/release-notes/2.0.2.md
modified:   docs/release-notes/2.0.2.md
=> PBM-992 Added the CVE fix to the release notes

_resource/overrides/main.html
The footer in the template pointed to the PostgreSQL forum and Jira project.
Update to point to the correct PBM resource.
=> Update links in `main.html` template

_resource/overrides/main.html
modified:   _resource/overrides/main.html
=> PBM-996 Added Google Tag manager to docs to enable tracking

docs/installation.md
=> PBM-1018 Updated the list of tools within a package

docs/usage/incremental-backup.md
The correct version is 2.0.3 not 2.3.0
=> Incremental physical backups - fix version

variables.yml
Fix release version so that index.html includes correct version (2.0.3) and correct link to release notes.
Thanks,
=> Fix release version in variables.yml

docs/index.md
Updated intro description
Removed disclaimer from PITR in index
=> PBM-1023 Removed false tech preview label

_resource/overrides/main.html, _resource/overrides/partials/header.html, _resource/overrides/partials/nav.html, mkdocs-base.yml, mkdocs.yml, requirements.txt
modified:   _resource/overrides/main.html
modified:   _resource/overrides/partials/header.html
modified:   _resource/overrides/partials/nav.html
modified:   mkdocs.yml
=> PBM-1024 Project adjustment to apply Material 9.0

docs/details/backup-types.md, docs/details/logical.md, docs/details/physical.md, docs/index.md, docs/release-notes/0.5.0.md, docs/usage/incremental-backup.md, docs/usage/oplog-replay.md, mkdocs-base.yml
Created a separate section
Created backup overview page
modified:   docs/details/backup-types.md
new file:   docs/details/logical.md
new file:   docs/details/physical.md
modified:   docs/index.md
modified:   docs/release-notes/0.5.0.md
modified:   docs/usage/incremental-backup.md
modified:   docs/usage/oplog-replay.md
=> PBM-1023 backup types rework

docs/index.md, docs/usage/point-in-time-recovery.md
modified:   docs/index.md
modified:   docs/usage/point-in-time-recovery.md
=> PBM-1022 Rework PITR

docs/release-notes.md, docs/release-notes/2.0.4.md, mkdocs-base.yml, variables.yml
new file:   docs/release-notes/2.0.4.md
=> PBM-1051 Release notes 2.0.4

docs/usage/start-backup.md
It is `--type=physical` not `--type-physical` otherwise the command will not work.
=> Fix command to start physical backup

docs/reference/pbm-commands.md, docs/usage/delete-backup.md, docs/usage/schedule-backup.md
docs/reference/pbm-commands.md
modified:   docs/usage/delete-backup.md
modified:   docs/usage/schedule-backup.md
=> PBM-850 Documented cleanup of backup storage

docs/install/initial-setup.md
Added information where specific steps need to be executed (it was unclear)
=> Improve initial-setup page

docs/features/backup-types.md, docs/features/incremental-backup.md, docs/usage/restore.md, docs/usage/start-backup.md
modified:   docs/features/backup-types.md
modified:   docs/features/incremental-backup.md
=> PBM-1035 Added a warning about incompatibility with previous backups

docs/reference/configuration-options.md
modified:   docs/reference/configuration-options.md
=> PBM-1060 Added AWS token description to config options

docs/usage/restore.md
=> PBM-1066 Described restore from a backup with different FCV

docs/usage/restore.md
=> PBM-1070 Added a note how to track phys restore progress

docs/details/deployments.md, docs/usage/restore.md, mkdocs-base.yml
modified:   docs/details/deployments.md
=> PBM-979 Documented support of arbiter nodes for physical restores

docs/reference/pbm-commands.md
=> PBM-1085 Added yes to commands with force

docs/usage/restore.md
=> Updated link to a blog post

docs/release-notes/1.4.0.md
modified:   docs/release-notes/1.4.0.md
=> Fixed release date for PBM 1.4.0

docs/features/backup-types.md, docs/features/incremental-backup.md
modified:   docs/features/backup-types.md
modified:   docs/features/incremental-backup.md
=> PPM-1128  Added supported PSMDB versions for incremental backup

docs/usage/restore.md
=> PBM-1102 Added a note about a confusing log message

docs/usage/start-backup.md
- Missing dots
- Missing dash in --type
=> Start backup - quick fixes

docs/reference/pitr-options.md, docs/usage/oplog-replay.md, docs/usage/start-backup.md
modified:   docs/reference/pitr-options.md
modified:   docs/usage/oplog-replay.md
=> Extended the description of oplogOnly command

mkdocs.yml
=> PBM-1149 Adjusted site-url in doc site config

docs/reference/pbm-commands.md
=> PBM-1132 Amended --ns description to mention logocal backups

docs/usage/restore.md
=> PBM-1055 Added support for remapping during physical/incremental restore

docs/release-notes.md, docs/release-notes/2.2.1.md, mkdocs-base.yml, variables.yml
new file:   docs/release-notes/2.2.1.md
=> PBM-1156 Release notes 2.2.1

mkdocs-pdf.yml
=> Improvements from HD-20808 to PDF output

_resource/overrides/partials/nav.html
Keep our customizations in place
modified:   _resource/overrides/partials/nav.html
=> Updated nav.html for 9.2 version of Material theme

docs/features/physical.md
modified:   docs/features/physical.md
=> PBM-1171 Physical backups in mixed deployments

docs/install/docker.md
=> PBM-1215 Removed install editor step as it is part of the image now

docs/reference/pbm-commands.md
=> DOCS-96 Fixed pbm cleanup command in reference

docs/release-notes/2.4.0.md
The Jira ticket title was updated as well after a team discussion. Updating its mention in the RN now, to avoid confusion and for consistency. Thanks
=> Update description of issue PBM-1223 in 2.4.0 release notes

docs/release-notes.md, docs/release-notes/2.4.1.md, mkdocs-base.yml, variables.yml
new file:   docs/release-notes/2.4.1.md
=> PBM-1266 Release notes 2.4.1

_resource/overrides/main.html
modified:   _resource/overrides/main.html'
=> PBM-1315 Added PostHog script to docs

docs/features/selective-backup.md, docs/reference/pbm-commands.md, docs/usage/restore.md
Documented selective restore with users and roles
modified:   docs/features/selective-backup.md
=> PBM-1213 Doc-restore-users-roles

docs/features/comparison.md, docs/features/multi-storage.md, docs/reference/pbm-commands.md, mkdocs-base.yml
modified:   docs/features/comparison.md
new file:   docs/features/multi-storage.md
=> PBM-1228 Documented multiple storages for backups

docs/usage/restore.md
=> PBM-1264 Updated before you start steps for logical restore

docs/usage/delete-backup.md
modified:   docs/usage/delete-backup.md
=> PBM-1385 Added explanation about valid base backup for PITR

docs/features/point-in-time-recovery.md
modified:   docs/features/point-in-time-recovery.md
=> PBM-1388 Extended the description of how oplogs are saved

docs/reference/pbm-commands.md, docs/usage/restore-progress.md
modified:   docs/usage/restore-progress.md
=> PBM-1338 Documented new fields for the describe-restore output

docs/release-notes.md, docs/release-notes/2.7.0.md, mkdocs-base.yml, variables.yml
new file:   docs/release-notes/2.7.0.md
=> PBM-1402 Release notes 2.7.0

docs/details/storage-config-example.md, docs/install/backup-storage.md, mkdocs.yml
modified:   docs/details/storage-config-example.md
modified:   docs/install/backup-storage.md
modified:   mkdocs.yml
=> PBM-1108 Added a requirement for a dedicated S3 bucket for PBM

docs/reference/configuration-options.md
modified: `docs/reference/configuration-options.md`
=> update retry delays example and description

docs/details/versions.md
modified:   docs/details/versions.md
=> Fixed 8.0.x link in versions table

docs/css/design.css, docs/css/nocopy.css, mkdocs-base.yml
modified:   docs/css/design.css
=> Fix code blocks copy button

docs/install/repos.md
new file:   docs/install/repos.md
=> Added a separate page for installing on AL2023

docs/usage/backup-incremental.md, docs/usage/backup-physical.md
=> Igroene patch 3

.github/styles/config/vocabularies/Percona/accept.txt, docs/reference/config.md, docs/reference/pbm-commands.md
Based on discussion [here](https://perconacorp.slack.com/archives/CARSRTYNB/p1744225055282189?thread_ts=1744224919.313919&cid=CARSRTYNB).
=> Add more info for --force-resync option

.gitignore, docs/usage/pitr-physical.md
Added how to track the progress
modified:   docs/usage/pitr-physical.md
=> PBM-1533 Removed -w flag from physical pitr guide

.gitignore, docs/features/restore-remapping.md
modified:   docs/features/restore-remapping.md
=> PBM-1545 Clarified mapping order for restore

.gitignore, docs/details/storage-configuration.md
Describe a solution for Custom S3 TLS Certificate support in PBM
=> PBM-1525 Custom S3 TLS Certificate support in PBM

docs/_templates/pdf_cover_page.tpl, docs/reference/configuration-options.md, docs/release-notes.md, docs/release-notes/2.10.0.md, docs/release-notes/2.8.0.md, docs/troubleshoot/index.md, docs/troubleshoot/restore-partial.md, mkdocs-base.yml, variables.yml
new file:   docs/release-notes/2.10.0.md
=> PBM-1576-Release notes 2.10.0
