source/backup-types.rst, source/index.rst
WiredTiger is the only supported storage engine in PSMDB
modified:   source/backup-types.rst
modified:   source/index.rst
=> PBM-844 Added the condition for physical backups

source/schedule-backup.rst
Noticed this typo on the "Schedule backups" docs page that might trip up some users.
=> Fix etc directory name typo in schedule backups docs page

source/.res/code-block/bash/pbm-agent-mongodb-conn-string-examples.txt, source/.res/code-block/bash/pbm-cli-mongodb-conn-string-examples.txt, source/authentication.rst
modified:   source/.res/code-block/bash/pbm-agent-mongodb-conn-string-examples.txt
modified:   source/.res/code-block/bash/pbm-cli-mongodb-conn-string-examples.txt
modified:   source/authentication.rst
=> PBM-720 Described the use of authSource and defaultauthdb

docs/usage/selective-backup.md
In the Selective backup section, the `--ns` flag in both commands only has one hyphen (`-`) instead of two (`--`)
=> Correcting the Selective backup commands

docs/features/backup-types.md, docs/index.md, docs/release-notes.md, docs/release-notes/2.1.0.md, docs/release-notes/2.2.0.md, docs/usage/restore.md, mkdocs-base.yml, variables.yml
new file:   docs/release-notes/2.2.0.md
=> PBM-1131 Release notes 2.2.0

docs/usage/pitr-tutorial.md
`--base-backup` is a wrong command, as per reference guide `--base-snapshot` should be used instead.
=> Update pitr-tutorial.md - wrong command for pitr restore

docs/reference/pbm-commands.md, docs/usage/describe-backup.md
modified:   docs/usage/describe-backup.md
=> PBM-848 Documented describe backup with collections

README.md, _resource/overrides/partials/nav.html, docs/details/versions.md
modified:   README.md
modified:   docs/details/versions.md
=> PBM-1179 Added supported versions matrix

docs/details/storage-configuration.md, docs/reference/config.md
modified:   docs/details/storage-configuration.md
modified:   docs/reference/config.md
=> PBM-1194 Added SSE-KMS configuration to SSE doc

docs/install/initial-setup.md
`endpointUrl` might be needed in some cases, for instance when using AWS PrivateLink.
Thanks,
---
**Was:**
**Now:**
=> s3 remote storage - adds the PrivateLink case

docs/features/snapshots.md
modified:   docs/features/snapshots.md
=> PBM-1221 Added a note how to make external restore when using filesystem

docs/installation.md, docs/pmm.md, mkdocs-base.yml
modified:   docs/installation.md
new file:   docs/pmm.md
=> PBM-1209 Added min system requirements to run PBM

docs/features/backup-types.md
https://jira.percona.com/browse/PBM-1007
=> selective backup supported on sharded collection starts from PBM 2.1.0

docs/reference/pbm-commands.md, docs/usage/delete-backup.md, docs/usage/schedule-backup.md, mkdocs-base.yml
modified:   docs/usage/delete-backup.md
modified:   docs/usage/schedule-backup.md
=> PBM-1141 Documented deleted backup by type

docs/install/repos.md
modified:   docs/install/repos.md
=> Added install on ARM64 instructions

docs/features/point-in-time-recovery.md, docs/reference/backup-options.md, docs/usage/restore.md, docs/usage/start-backup.md, mkdocs-pdf.yml
modified:   docs/features/point-in-time-recovery.md
modified:   docs/reference/backup-options.md
modified:   mkdocs-pdf.yml
=> PBM-907 Doc: Don't stop PITR during backup

docs/usage/restore-progress.md
docs/usage/restore-progress.md
=> PBM-1337 Added link to the output from the Track restore progress page

docs/features/backup-types.md, docs/features/snapshots.md
modified:   docs/features/backup-types.md
modified:   docs/features/snapshots.md
=> Replaced tech preview label with GA

docs/features/point-in-time-recovery.md, docs/installation.md, docs/reference/pbm-commands.md, docs/reference/pitr-options.md
docs/features/point-in-time-recovery.md
=> PBM-1043 PITR node priority

docs/reference/pbm-commands.md
modified:   docs/reference/pbm-commands.md'
=> PBM-1303 Added --wait-time flag to pbm command reference

docs/details/architecture.md, docs/details/pbm-agent.md, docs/install/initial-setup.md
Adds a warning re PBM agents and election process.
Also, excludes arbiters in `architecture` and `pbm-agent` as done already on `initial-setup`.
=> PBM-1383 - highlight more word `every` and mention election process

docs/details/authentication.md, docs/install/configure-authentication.md
modified:   docs/details/authentication.md
modified:   docs/install/configure-authentication.md
=> PBM-1351 Added a section of support of EKS

docs/features/point-in-time-recovery.md, docs/features/selective-backup.md, docs/usage/start-backup.md
modified:   docs/features/point-in-time-recovery.md
modified:   docs/features/selective-backup.md
=> PBM-1389 Documented limitations for ops for MongoDB 8.0

docs/details/versions.md
Split into separate ones for MongoDB and PSMDB
Added version 2.7.0 to each
modified:   docs/details/versions.md
=> PBM-1419 Reworked supported versions matrix

docs/usage/restore.md
Fixing two issues.
**1.** Wrong indentation causes wrong number in numbered list 
Before:
**Now:**
**2.** Wrong indentation
Before:
**Now:**
---
Thanks,
=> Restore page - indentation fixes

docs/reference/pbm-commands.md, docs/troubleshoot/pbm-report.md, mkdocs-base.yml
new file:   docs/troubleshoot/pbm-report.md
=> PBM-887 Documented pbm diagnostic command

docs/features/selective-backup.md, docs/reference/pbm-commands.md, docs/usage/restore.md
modified:   docs/features/selective-backup.md
=> PBM-1427 Documented how to clone collections

docs/manage/logpath.md, mkdocs-base.yml
new file:   docs/manage/logpath.md
=> PBM-1226 Documented custom log path configuration

.github/styles/config/vocabularies/Percona/accept.txt, docs/details/storage-configuration.md, docs/install/backup-storage.md, mkdocs-base.yml
Added examples of bucket creation in different providers. Also some minor corrections to the backup storage section
=> Igroene patch 5

docs/install/docker.md
- https://hub.docker.com/repository/docker/percona/percona-backup-mongodb requires login
- https://hub.docker.com/r/percona/percona-backup-mongodb seems the correct one, and similar to the link we are using in the documentation of other products
Thanks,
=> Fix docker link

docs/details/gcs.md, docs/details/s3-storage.md, docs/install/backup-storage.md, docs/reference/configuration-options.md, mkdocs-base.yml
modified:   docs/details/storage-config-example.md
modified:   docs/reference/configuration-options.md
=> PBM-1484 Updated GCS configuration example and options

docs/usage/restore-selective.md, mkdocs-base.yml
As documented in https://docs.percona.com/percona-backup-mongodb/usage/restore-selective.html, it is possible to do a selective restore either from a full or a selective backup.
However the title of this page is currently "Restore from a selective logical backup" which mistakenly makes you think that this page is about restoring from a selective backup - but as wrote above restore from full backup is supported as well.
I am therefore proposing we change the title of this page to:
"Make a selective restore"
This would keep things more general, and less confusing, in my opinion, Other ideas welcome.
Thanks!
=> Fix title of the selective restore section

docs/features/known-limitations.md
Updated limitations for selective backups and restores, including sharded collections and multi-collection transactions.
=> PBM-1561 Revise known limitations for backups and restores

.github/styles/config/vocabularies/Percona/accept.txt, docs/details/storage-configuration.md, docs/features/split-merge-backup.md, docs/reference/configuration-options.md, mkdocs-base.yml
modified:   docs/details/storage-configuration.md
new file:   docs/features/split-merge-backup.md
modified: docs/reference/configuration-options.md
=> PBM-1490-Documented the ability to set file size limit for large backups

docs/usage/restore-physical.md
modified:   docs/usage/restore-physical.md
=> PBM-1612 Added the check for the restart policy for mongod process to restore considerations
